### ISSUE TITLE
Which script to use for training RL agent?

### ISSUE THREAD

**Issue by JeromeNi** [andybi7676/reborn-uasr#2]
Hello, currently I see three scripts for training the RL agent,  train_rl_cnnagent.py, train_rl_cnnagent_enpei_standardPPL.py, train_rl_cnnagent_enpei.py and  train_rl_cnnagent_lhz.py. Out of the four, which one should I use to train the same RL agent as reported in the paper?

**Comment by andybi7676** [comment]
Hi, JeromeNi. Please use train_rl_cnnagent_enpei.py to train the segmenter currently. We will organize the code base as soon as possible. By the way, if you have other questions, please feel free to raise them continually in the first issue, as I will close this one. I appreciate your understanding.
